#pragma once
using TextureID = uint32_t;
constexpr TextureID begin_game = 2;
constexpr TextureID leaderboard = 3;
constexpr TextureID quit = 4;
constexpr TextureID register_img = 5;
constexpr TextureID sf_kunkun_begin = 6;
constexpr TextureID sf_kunkun_end = 338;
constexpr TextureID sf_md_begin = 338;
constexpr TextureID sf_md_end = 368;
constexpr TextureID sf_test_begin = 368;
constexpr TextureID sf_test_end = 386;
