#pragma once
#include <core/frame/app.hpp>
#include <core/frame/window.hpp>
#include <core/render/BatchRenderer.hpp>
#include <interface/general_page.hpp>
#include <interface/button.hpp>
#include <component/button/simple_button.hpp>
#include <component/button/simple_texture_button_style.hpp>
#include <component/button/simple_text_button_style.hpp>
#include <component/input/input_box_style.hpp>
