#pragma once
#include <core/frame/App.hpp>
#include <core/frame/Window.hpp>
#include <core/render/BatchRenderer.hpp>
#include <interface/IGeneralPage.hpp>
#include <interface/IButton.hpp>
#include <component/button/simple_button.hpp>
#include <component/button/simple_texture_button_style.hpp>
#include <component/button/simple_text_button_style.hpp>
#include <component/input/InputBoxStyle.hpp>
#include <component/graph/IGraph.hpp>
#include <component/graph/Rect.hpp>
#include <core/tool/Point.hpp>
