var annotated_dup =
[
    [ "dao", "namespacedao.html", [
      [ "SimpleButton", "classdao_1_1SimpleButton.html", "classdao_1_1SimpleButton" ],
      [ "Image", "classdao_1_1Image.html", "classdao_1_1Image" ],
      [ "AtlasTexture", "classdao_1_1AtlasTexture.html", "classdao_1_1AtlasTexture" ],
      [ "App", "classdao_1_1App.html", "classdao_1_1App" ],
      [ "AppCommand", "structdao_1_1AppCommand.html", "structdao_1_1AppCommand" ],
      [ "AppController", "classdao_1_1AppController.html", "classdao_1_1AppController" ],
      [ "Window", "classdao_1_1Window.html", "classdao_1_1Window" ],
      [ "Tray", "classdao_1_1Tray.html", "classdao_1_1Tray" ],
      [ "Context", "classdao_1_1Context.html", "classdao_1_1Context" ],
      [ "SwitchDeleter", "classdao_1_1SwitchDeleter.html", "classdao_1_1SwitchDeleter" ],
      [ "AtlasDrawBatch", "structdao_1_1AtlasDrawBatch.html", "structdao_1_1AtlasDrawBatch" ],
      [ "VertexBatchBuilder", "classdao_1_1VertexBatchBuilder.html", "classdao_1_1VertexBatchBuilder" ],
      [ "AtlasRegion", "structdao_1_1AtlasRegion.html", "structdao_1_1AtlasRegion" ],
      [ "Page", "classdao_1_1Page.html", "classdao_1_1Page" ],
      [ "WindowCommand", "structdao_1_1WindowCommand.html", "structdao_1_1WindowCommand" ],
      [ "WindowController", "classdao_1_1WindowController.html", "classdao_1_1WindowController" ],
      [ "MappedRegion", "classdao_1_1MappedRegion.html", "classdao_1_1MappedRegion" ],
      [ "GlyphAtlas", "classdao_1_1GlyphAtlas.html", "classdao_1_1GlyphAtlas" ],
      [ "Text", "classdao_1_1Text.html", "classdao_1_1Text" ],
      [ "BoundingBox", "classdao_1_1BoundingBox.html", "classdao_1_1BoundingBox" ],
      [ "GeneralPage", "classdao_1_1GeneralPage.html", "classdao_1_1GeneralPage" ],
      [ "AnimatedSprite", "classdao_1_1AnimatedSprite.html", "classdao_1_1AnimatedSprite" ],
      [ "SimpleTextButtonStyle", "classdao_1_1SimpleTextButtonStyle.html", "classdao_1_1SimpleTextButtonStyle" ],
      [ "SimpleTextureButtonStyle", "classdao_1_1SimpleTextureButtonStyle.html", "classdao_1_1SimpleTextureButtonStyle" ],
      [ "GeometryVertex", "structdao_1_1GeometryVertex.html", "structdao_1_1GeometryVertex" ],
      [ "Geometry", "classdao_1_1Geometry.html", "classdao_1_1Geometry" ],
      [ "InputBox", "classdao_1_1InputBox.html", "classdao_1_1InputBox" ],
      [ "InputBoxStyle", "classdao_1_1InputBoxStyle.html", "classdao_1_1InputBoxStyle" ],
      [ "Rectangle", "classdao_1_1Rectangle.html", "classdao_1_1Rectangle" ],
      [ "ColorRGBA", "structdao_1_1ColorRGBA.html", "structdao_1_1ColorRGBA" ],
      [ "RingVector", "classdao_1_1RingVector.html", "classdao_1_1RingVector" ],
      [ "TickTimer", "classdao_1_1TickTimer.html", "classdao_1_1TickTimer" ],
      [ "Button", "classdao_1_1Button.html", "classdao_1_1Button" ],
      [ "ButtonStyle", "classdao_1_1ButtonStyle.html", "classdao_1_1ButtonStyle" ],
      [ "Drawable", "classdao_1_1Drawable.html", "classdao_1_1Drawable" ]
    ] ]
];