var annotated_dup =
[
    [ "dao", "namespacedao.html", [
      [ "ifc", "namespacedao_1_1ifc.html", [
        [ "IPage", "classdao_1_1ifc_1_1IPage.html", "classdao_1_1ifc_1_1IPage" ],
        [ "IGeneralPage", "classdao_1_1ifc_1_1IGeneralPage.html", "classdao_1_1ifc_1_1IGeneralPage" ],
        [ "IGraph", "classdao_1_1ifc_1_1IGraph.html", "classdao_1_1ifc_1_1IGraph" ],
        [ "IButton", "classdao_1_1ifc_1_1IButton.html", "classdao_1_1ifc_1_1IButton" ],
        [ "IButtonStyle", "classdao_1_1ifc_1_1IButtonStyle.html", "classdao_1_1ifc_1_1IButtonStyle" ],
        [ "IDrawable", "classdao_1_1ifc_1_1IDrawable.html", "classdao_1_1ifc_1_1IDrawable" ]
      ] ],
      [ "SimpleButton", "classdao_1_1SimpleButton.html", "classdao_1_1SimpleButton" ],
      [ "Image", "classdao_1_1Image.html", "classdao_1_1Image" ],
      [ "App", "classdao_1_1App.html", "classdao_1_1App" ],
      [ "AppCommand", "structdao_1_1AppCommand.html", "structdao_1_1AppCommand" ],
      [ "AppController", "classdao_1_1AppController.html", "classdao_1_1AppController" ],
      [ "Window", "classdao_1_1Window.html", "classdao_1_1Window" ],
      [ "Tray", "classdao_1_1Tray.html", "classdao_1_1Tray" ],
      [ "Context", "classdao_1_1Context.html", "classdao_1_1Context" ],
      [ "FrameLimiter", "classdao_1_1FrameLimiter.html", "classdao_1_1FrameLimiter" ],
      [ "SwitchDeleter", "classdao_1_1SwitchDeleter.html", "classdao_1_1SwitchDeleter" ],
      [ "AtlasDrawBatch", "structdao_1_1AtlasDrawBatch.html", "structdao_1_1AtlasDrawBatch" ],
      [ "BatchRenderer", "classdao_1_1BatchRenderer.html", "classdao_1_1BatchRenderer" ],
      [ "WindowCommand", "structdao_1_1WindowCommand.html", "structdao_1_1WindowCommand" ],
      [ "WindowController", "classdao_1_1WindowController.html", "classdao_1_1WindowController" ],
      [ "AtlasTexture", "classdao_1_1AtlasTexture.html", "classdao_1_1AtlasTexture" ],
      [ "GlyphAtlas", "classdao_1_1GlyphAtlas.html", "classdao_1_1GlyphAtlas" ],
      [ "Text", "classdao_1_1Text.html", "classdao_1_1Text" ],
      [ "Triangle", "classdao_1_1Triangle.html", "classdao_1_1Triangle" ],
      [ "AtlasRegion", "structdao_1_1AtlasRegion.html", "structdao_1_1AtlasRegion" ],
      [ "MappedRegion", "classdao_1_1MappedRegion.html", "classdao_1_1MappedRegion" ],
      [ "BoundingBox", "classdao_1_1BoundingBox.html", "classdao_1_1BoundingBox" ],
      [ "ColorRGBA", "classdao_1_1ColorRGBA.html", "classdao_1_1ColorRGBA" ],
      [ "Vertex", "classdao_1_1Vertex.html", "classdao_1_1Vertex" ],
      [ "AnimatedSprite", "classdao_1_1AnimatedSprite.html", "classdao_1_1AnimatedSprite" ],
      [ "SimpleTextButtonStyle", "classdao_1_1SimpleTextButtonStyle.html", "classdao_1_1SimpleTextButtonStyle" ],
      [ "SimpleTextureButtonStyle", "classdao_1_1SimpleTextureButtonStyle.html", "classdao_1_1SimpleTextureButtonStyle" ],
      [ "Circle", "classdao_1_1Circle.html", "classdao_1_1Circle" ],
      [ "MaxPolygon", "classdao_1_1MaxPolygon.html", "classdao_1_1MaxPolygon" ],
      [ "Polygon", "classdao_1_1Polygon.html", "classdao_1_1Polygon" ],
      [ "Rect", "classdao_1_1Rect.html", "classdao_1_1Rect" ],
      [ "SolidCircle", "classdao_1_1SolidCircle.html", "classdao_1_1SolidCircle" ],
      [ "SolidRect", "classdao_1_1SolidRect.html", "classdao_1_1SolidRect" ],
      [ "InputBox", "classdao_1_1InputBox.html", "classdao_1_1InputBox" ],
      [ "InputBoxStyle", "classdao_1_1InputBoxStyle.html", "classdao_1_1InputBoxStyle" ],
      [ "Point", "classdao_1_1Point.html", "classdao_1_1Point" ],
      [ "RingVector", "classdao_1_1RingVector.html", "classdao_1_1RingVector" ],
      [ "TickTimer", "classdao_1_1TickTimer.html", "classdao_1_1TickTimer" ]
    ] ]
];